spring:
  application:
    name: aipets-app 
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always

#org.springframework.cloud.bindings.boot.enable: true

logging:
  level:    
    org.springframework.cloud.bindings: DEBUG