apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: birdogss
  labels:
    app.kubernetes.io/name: birdogss      
    app.kubernetes.io/part-of: micropets
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    micropets/kind: backend
spec:
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/my-birdogss-svc
      ref:
        branch: main  
  params:
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: bmoussaud
    - name: gitops_repository_name
      value: micropets-app-gitops
    - name: port
      value: 8080
    - name: observability
      value: false
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"     
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
