apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: aipets-springboot
  labels:
    app.kubernetes.io/name: aipets
    app.kubernetes.io/part-of: micropets
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    micropets/kind: backend
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_SPRING_CLOUD_BINDINGS_DISABLED
        value: "true"
  serviceAccountName: tap-default
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: aipets-config
  source:
    git:
      url: https://github.com/bmoussaud/micropets-aipets-springboot
      ref:
        branch: main
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: userId
      value: 1001
  env:
    - name: org.springframework.cloud.bindings.boot.enable
      value: "true"
